import express from "express";
import pg from "pg";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),PORT=Number(process.env.PORT||3000),prod=process.env.NODE_ENV==="production";
const dbUrl=process.env.DATABASE_URL||"";\nconst pool=dbUrl?new pg.Pool({connectionString:dbUrl,ssl:/railway\\.internal/i.test(dbUrl)?false:(prod?{rejectUnauthorized:false}:undefined),max:10}):null;
app.disable("x-powered-by");app.use(express.json({limit:"2mb"}));
const buckets=new Map();const rate=(name,max=60,win=60000)=>(req,res,next)=>{const k=name+":"+(req.ip||"unknown"),now=Date.now();let b=buckets.get(k);if(!b||now-b.t>win)b={t:now,n:0};if(++b.n>max)return res.status(429).json({error:"Too many requests"});buckets.set(k,b);next()};
const db=async(sql,p=[])=>pool?pool.query(sql,p):null, bad=(res,c,m)=>res.status(c).json({error:m}), text=(v,m=500)=>String(v??"").trim().slice(0,m), email=v=>text(v,200).toLowerCase();
function pw(pass,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(pass,salt,64).toString("hex")}}function verify(pass,s,h){const a=crypto.scryptSync(pass,s,64),b=Buffer.from(h,"hex");return b.length===a.length&&crypto.timingSafeEqual(a,b)}
const token=()=>crypto.randomBytes(32).toString("hex"),th=t=>crypto.createHash("sha256").update(t).digest("hex");
function ck(n,v,age){return n+"="+encodeURIComponent(v)+"; Path=/; HttpOnly; SameSite=Lax; Max-Age="+age+(prod?"; Secure":"")}function clear(n){return n+"=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"+(prod?"; Secure":"")}
function getToken(req){const m=(req.headers.cookie||"").match(/(?:^|;\\s*)nexus_session=([^;]+)/);return m?decodeURIComponent(m[1]):""}
app.use((req,res,next)=>{if(["POST","PUT","PATCH","DELETE"].includes(req.method)){const o=req.get("origin"),h=req.get("host");if(o&&!o.endsWith("://"+h))return bad(res,403,"Invalid request origin")}next()});
async function user(req){if(!pool)return null;const t=getToken(req);if(!t)return null;return(await db("SELECT u.id,u.email,u.display_name,u.avatar_url,u.role,s.expires_at FROM nexus_sessions s JOIN nexus_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()",[th(t)])).rows[0]||null}
async function auth(req,res,next){try{req.user=await user(req);if(!req.user)return bad(res,401,"Authentication required");next()}catch(e){next(e)}}
async function ws(req,res,next){try{const id=req.params.workspaceId||req.body.workspace_id||req.query.workspace_id;req.workspace=(await db("SELECT w.*,wm.role member_role FROM nexus_workspaces w JOIN nexus_workspace_members wm ON wm.workspace_id=w.id WHERE w.id=$1 AND wm.user_id=$2",[id,req.user.id])).rows[0];if(!req.workspace)return bad(res,404,"Workspace not found");next()}catch(e){next(e)}}
const writable=r=>["owner","admin","editor"].includes(r);
async function ev(w,u,type,p={}){if(pool&&w)await db("INSERT INTO nexus_events(workspace_id,user_id,type,payload) VALUES($1,$2,$3,$4)",[w,u,type,p])}
const slug=v=>text(v,70).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,55)||"workspace";
async function init(){if(!pool)return;await db(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS nexus_users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,display_name TEXT NOT NULL DEFAULT 'Operator',avatar_url TEXT DEFAULT '',role TEXT NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_sessions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID REFERENCES nexus_users(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_workspaces(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,description TEXT DEFAULT '',owner_id UUID REFERENCES nexus_users(id) ON DELETE CASCADE,layout JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_workspace_members(workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,user_id UUID REFERENCES nexus_users(id) ON DELETE CASCADE,role TEXT DEFAULT 'editor',created_at TIMESTAMPTZ DEFAULT now(),PRIMARY KEY(workspace_id,user_id));
CREATE TABLE IF NOT EXISTS nexus_projects(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_apps(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,slug TEXT NOT NULL,description TEXT DEFAULT '',status TEXT DEFAULT 'draft',config JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(workspace_id,slug));
CREATE TABLE IF NOT EXISTS nexus_modules(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),project_id UUID REFERENCES nexus_projects(id) ON DELETE CASCADE,app_id UUID REFERENCES nexus_apps(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT NOT NULL,config JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_builder_nodes(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,app_id UUID REFERENCES nexus_apps(id) ON DELETE CASCADE,type TEXT NOT NULL,label TEXT NOT NULL,x NUMERIC DEFAULT 80,y NUMERIC DEFAULT 80,config JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_automations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,trigger_type TEXT DEFAULT 'manual',enabled BOOLEAN DEFAULT false,definition JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_events(id BIGSERIAL PRIMARY KEY,workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,user_id UUID REFERENCES nexus_users(id) ON DELETE SET NULL,type TEXT NOT NULL,payload JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS nexus_events_ws_time ON nexus_events(workspace_id,created_at DESC);
ALTER TABLE nexus_users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE nexus_users ADD COLUMN IF NOT EXISTS password_salt TEXT;
ALTER TABLE nexus_users ADD COLUMN IF NOT EXISTS display_name TEXT DEFAULT 'Operator';
ALTER TABLE nexus_users ADD COLUMN IF NOT EXISTS avatar_url TEXT DEFAULT '';
ALTER TABLE nexus_users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE nexus_projects ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE;
ALTER TABLE nexus_modules ADD COLUMN IF NOT EXISTS app_id UUID REFERENCES nexus_apps(id) ON DELETE CASCADE;
ALTER TABLE nexus_events ADD COLUMN IF NOT EXISTS workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE;
ALTER TABLE nexus_events ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES nexus_users(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS nexus_ai_agents(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT DEFAULT '',model TEXT DEFAULT 'local',enabled BOOLEAN DEFAULT true,config JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_files(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,path TEXT NOT NULL,size_bytes BIGINT DEFAULT 0,mime_type TEXT DEFAULT 'application/octet-stream',version INTEGER DEFAULT 1,metadata JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now(),UNIQUE(workspace_id,path));
CREATE TABLE IF NOT EXISTS nexus_marketplace_items(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,kind TEXT NOT NULL,description TEXT DEFAULT '',version TEXT DEFAULT '0.1.0',status TEXT DEFAULT 'draft',manifest JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_api_keys(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,key_hash TEXT UNIQUE NOT NULL,key_prefix TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now(),last_used_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS nexus_agents_ws ON nexus_ai_agents(workspace_id);
CREATE INDEX IF NOT EXISTS nexus_files_ws ON nexus_files(workspace_id);
CREATE INDEX IF NOT EXISTS nexus_market_ws ON nexus_marketplace_items(workspace_id);
CREATE TABLE IF NOT EXISTS nexus_webhooks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,url TEXT NOT NULL,secret_hash TEXT NOT NULL,events JSONB DEFAULT '[]'::jsonb,enabled BOOLEAN DEFAULT true,created_at TIMESTAMPTZ DEFAULT now(),last_delivery_at TIMESTAMPTZ,last_status INTEGER);
CREATE TABLE IF NOT EXISTS nexus_jobs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,type TEXT NOT NULL,payload JSONB DEFAULT '{}'::jsonb,status TEXT DEFAULT 'queued',attempts INTEGER DEFAULT 0,max_attempts INTEGER DEFAULT 3,run_after TIMESTAMPTZ DEFAULT now(),locked_at TIMESTAMPTZ,last_error TEXT,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS nexus_jobs_ready ON nexus_jobs(status,run_after);
CREATE TABLE IF NOT EXISTS nexus_media_projects(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),workspace_id UUID REFERENCES nexus_workspaces(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT DEFAULT 'audio',settings JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now(),updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_media_tracks(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),media_project_id UUID REFERENCES nexus_media_projects(id) ON DELETE CASCADE,name TEXT NOT NULL,kind TEXT DEFAULT 'audio',position INTEGER DEFAULT 0,settings JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS nexus_media_clips(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),track_id UUID REFERENCES nexus_media_tracks(id) ON DELETE CASCADE,name TEXT NOT NULL,start_ms BIGINT DEFAULT 0,duration_ms BIGINT DEFAULT 0,asset_path TEXT DEFAULT '',metadata JSONB DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS nexus_webhooks_ws ON nexus_webhooks(workspace_id);
CREATE INDEX IF NOT EXISTS nexus_media_projects_ws ON nexus_media_projects(workspace_id);
`)}
app.get("/health",async(_,res)=>{try{if(pool)await db("SELECT 1");res.json({ok:true,service:"NEXUS",database:!!pool,time:new Date().toISOString()})}catch(e){bad(res,503,e.message)}});
app.get("/api/auth/me",async(req,res,next)=>{try{const u=await user(req);res.json({authenticated:!!u,user:u||null})}catch(e){next(e)}});
app.post("/api/auth/register",rate("register",10),async(req,res,next)=>{try{if(!pool)return bad(res,503,"Database is not configured");const e=email(req.body.email),p=String(req.body.password||""),n=text(req.body.display_name,80)||"Operator";if(!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(e))return bad(res,400,"Enter a valid email");if(p.length<10)return bad(res,400,"Password must be at least 10 characters");if((await db("SELECT id FROM nexus_users WHERE email=$1",[e])).rows[0])return bad(res,409,"Account already exists");const h=pw(p),u=(await db("INSERT INTO nexus_users(email,password_hash,password_salt,display_name) VALUES($1,$2,$3,$4) RETURNING id,email,display_name,avatar_url,role,created_at",[e,h.hash,h.salt,n])).rows[0],w=(await db("INSERT INTO nexus_workspaces(name,slug,description,owner_id) VALUES($1,$2,$3,$4) RETURNING *",[n+"'s Command Center",slug(n)+"-"+crypto.randomBytes(3).toString("hex"),"Primary NEXUS workspace",u.id])).rows[0];await db("INSERT INTO nexus_workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[w.id,u.id]);const t=token();await db("INSERT INTO nexus_sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '30 days')",[u.id,th(t)]);res.setHeader("Set-Cookie",ck("nexus_session",t,2592000));await ev(w.id,u.id,"auth.registered",{email:e});res.status(201).json({user:u,workspace:w})}catch(e){next(e)}});
app.post("/api/auth/login",rate("login",20),async(req,res,next)=>{try{if(!pool)return bad(res,503,"Database is not configured");const e=email(req.body.email),p=String(req.body.password||""),u=(await db("SELECT * FROM nexus_users WHERE email=$1",[e])).rows[0];if(!u||!verify(p,u.password_salt,u.password_hash))return bad(res,401,"Email or password is incorrect");const t=token();await db("DELETE FROM nexus_sessions WHERE user_id=$1 OR expires_at<=now()",[u.id]);await db("INSERT INTO nexus_sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '30 days')",[u.id,th(t)]);res.setHeader("Set-Cookie",ck("nexus_session",t,2592000));const w=(await db("SELECT w.*,wm.role member_role FROM nexus_workspaces w JOIN nexus_workspace_members wm ON wm.workspace_id=w.id WHERE wm.user_id=$1 ORDER BY w.created_at",[u.id])).rows[0]||null;res.json({user:{id:u.id,email:u.email,display_name:u.display_name,avatar_url:u.avatar_url,role:u.role,created_at:u.created_at},workspace:w})}catch(e){next(e)}});
app.post("/api/auth/logout",async(req,res,next)=>{try{const t=getToken(req);if(pool&&t)await db("DELETE FROM nexus_sessions WHERE token_hash=$1",[th(t)]);res.setHeader("Set-Cookie",clear("nexus_session"));res.json({ok:true})}catch(e){next(e)}});
// Public API keys, webhook registry, background jobs, realtime stream, admin and media layers.
async function apiKey(req,res,next){try{const raw=(req.get("authorization")||"").replace(/^Bearer\\s+/i,"").trim();if(!raw||!pool)return bad(res,401,"API key required");const row=(await db("SELECT k.*,w.name workspace_name FROM nexus_api_keys k JOIN nexus_workspaces w ON w.id=k.workspace_id WHERE k.key_hash=$1",[th(raw)])).rows[0];if(!row)return bad(res,401,"Invalid API key");req.apiKey=row;await db("UPDATE nexus_api_keys SET last_used_at=now() WHERE id=$1",[row.id]);next()}catch(e){next(e)}}
app.get("/api/public/:workspaceId/ping",apiKey,async(req,res)=>{if(req.apiKey.workspace_id!==req.params.workspaceId)return bad(res,403,"Workspace mismatch");res.json({ok:true,workspace_id:req.apiKey.workspace_id,service:"NEXUS API"})});
app.get("/api/workspaces/:workspaceId/api-keys",ws,async(req,res,next)=>{try{res.json((await db("SELECT id,name,key_prefix,created_at,last_used_at FROM nexus_api_keys WHERE workspace_id=$1 ORDER BY created_at DESC",[req.workspace.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/api-keys",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100);if(!n)return bad(res,400,"Key name is required");const raw="nxs_"+crypto.randomBytes(30).toString("hex"),r=(await db("INSERT INTO nexus_api_keys(workspace_id,name,key_hash,key_prefix) VALUES($1,$2,$3,$4) RETURNING id,name,key_prefix,created_at",[req.workspace.id,n,th(raw),raw.slice(0,12)])).rows[0];await ev(req.workspace.id,req.user.id,"api_key.created",{id:r.id,name:n});res.status(201).json({...r,key:raw})}catch(e){next(e)}});
app.delete("/api/api-keys/:keyId",async(req,res,next)=>{try{const r=(await db("SELECT k.*,wm.role member_role FROM nexus_api_keys k JOIN nexus_workspace_members wm ON wm.workspace_id=k.workspace_id WHERE k.id=$1 AND wm.user_id=$2",[req.params.keyId,req.user.id])).rows[0];if(!r)return bad(res,404,"API key not found");if(!writable(r.member_role))return bad(res,403,"Write access required");await db("DELETE FROM nexus_api_keys WHERE id=$1",[r.id]);await ev(r.workspace_id,req.user.id,"api_key.deleted",{id:r.id});res.json({ok:true})}catch(e){next(e)}});
app.get("/api/workspaces/:workspaceId/webhooks",ws,async(req,res,next)=>{try{res.json((await db("SELECT id,name,url,events,enabled,created_at,last_delivery_at,last_status FROM nexus_webhooks WHERE workspace_id=$1 ORDER BY created_at DESC",[req.workspace.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/webhooks",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100),url=text(req.body.url,500);if(!n||!/^https?:\/\//i.test(url))return bad(res,400,"Webhook name and HTTP(S) URL are required");const secret=text(req.body.secret,200)||crypto.randomBytes(24).toString("hex"),r=(await db("INSERT INTO nexus_webhooks(workspace_id,name,url,secret_hash,events) VALUES($1,$2,$3,$4,$5) RETURNING id,name,url,events,enabled,created_at",[req.workspace.id,n,url,th(secret),JSON.stringify(Array.isArray(req.body.events)?req.body.events:[])])).rows[0];await ev(req.workspace.id,req.user.id,"webhook.created",{id:r.id,name:n});res.status(201).json({...r,secret})}catch(e){next(e)}});
app.patch("/api/webhooks/:webhookId",async(req,res,next)=>{try{const r=(await db("SELECT h.*,wm.role member_role FROM nexus_webhooks h JOIN nexus_workspace_members wm ON wm.workspace_id=h.workspace_id WHERE h.id=$1 AND wm.user_id=$2",[req.params.webhookId,req.user.id])).rows[0];if(!r)return bad(res,404,"Webhook not found");if(!writable(r.member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_webhooks SET enabled=COALESCE($1,enabled),events=COALESCE($2,events) WHERE id=$3 RETURNING id,name,url,events,enabled",[req.body.enabled==null?null:Boolean(req.body.enabled),Array.isArray(req.body.events)?JSON.stringify(req.body.events):null,r.id])).rows[0];res.json(o)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/jobs",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const type=text(req.body.type,80);if(!type)return bad(res,400,"Job type is required");const r=(await db("INSERT INTO nexus_jobs(workspace_id,type,payload,run_after) VALUES($1,$2,$3,COALESCE($4,now())) RETURNING *",[req.workspace.id,type,req.body.payload||{},req.body.run_after||null])).rows[0];await ev(req.workspace.id,req.user.id,"job.queued",{id:r.id,type});res.status(201).json(r)}catch(e){next(e)}});
app.get("/api/workspaces/:workspaceId/jobs",ws,async(req,res,next)=>{try{res.json((await db("SELECT id,type,payload,status,attempts,max_attempts,run_after,last_error,created_at,updated_at FROM nexus_jobs WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 100",[req.workspace.id])).rows)}catch(e){next(e)}});
app.get("/api/workspaces/:workspaceId/stream",ws,async(req,res)=>{res.setHeader("Content-Type","text/event-stream");res.setHeader("Cache-Control","no-cache");res.setHeader("Connection","keep-alive");res.flushHeaders?.();let last=new Date(0);let closed=false;const send=async()=>{if(closed)return;const rows=(await db("SELECT e.*,u.display_name FROM nexus_events e LEFT JOIN nexus_users u ON u.id=e.user_id WHERE e.workspace_id=$1 AND e.created_at>$2 ORDER BY e.created_at ASC LIMIT 50",[req.workspace.id,last])).rows;for(const e of rows){last=e.created_at;res.write("data: "+JSON.stringify(e)+"\\n\\n")}};await send();const timer=setInterval(()=>send().catch(()=>{}),1500);req.on("close",()=>{closed=true;clearInterval(timer)})});
app.get("/api/admin/overview",async(req,res,next)=>{try{if(!["admin","owner"].includes(req.user.role))return bad(res,403,"Admin access required");const [u,w,a,e,j]=await Promise.all([db("SELECT count(*)::int n FROM nexus_users"),db("SELECT count(*)::int n FROM nexus_workspaces"),db("SELECT count(*)::int n FROM nexus_apps"),db("SELECT count(*)::int n FROM nexus_events"),db("SELECT count(*)::int n FROM nexus_jobs WHERE status='queued'")]);res.json({users:u.rows[0].n,workspaces:w.rows[0].n,apps:a.rows[0].n,events:e.rows[0].n,queued_jobs:j.rows[0].n})}catch(e){next(e)}});
app.get("/api/workspaces/:workspaceId/media",ws,async(req,res,next)=>{try{const projects=(await db("SELECT * FROM nexus_media_projects WHERE workspace_id=$1 ORDER BY updated_at DESC",[req.workspace.id])).rows;for(const p of projects){p.tracks=(await db("SELECT * FROM nexus_media_tracks WHERE media_project_id=$1 ORDER BY position",[p.id])).rows;for(const t of p.tracks)t.clips=(await db("SELECT * FROM nexus_media_clips WHERE track_id=$1 ORDER BY start_ms",[t.id])).rows}res.json(projects)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/media/projects",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,120);if(!n)return bad(res,400,"Media project name is required");const r=(await db("INSERT INTO nexus_media_projects(workspace_id,name,type,settings) VALUES($1,$2,$3,$4) RETURNING *",[req.workspace.id,n,text(req.body.type,20)||"audio",req.body.settings||{}])).rows[0];await ev(req.workspace.id,req.user.id,"media.project.created",{id:r.id,name:n,type:r.type});res.status(201).json(r)}catch(e){next(e)}});
app.post("/api/media/projects/:projectId/tracks",async(req,res,next)=>{try{const r=(await db("SELECT p.*,wm.role member_role FROM nexus_media_projects p JOIN nexus_workspace_members wm ON wm.workspace_id=p.workspace_id WHERE p.id=$1 AND wm.user_id=$2",[req.params.projectId,req.user.id])).rows[0];if(!r)return bad(res,404,"Media project not found");if(!writable(r.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100)||"Track";const o=(await db("INSERT INTO nexus_media_tracks(media_project_id,name,kind,position,settings) VALUES($1,$2,$3,$4,$5) RETURNING *",[r.id,n,text(req.body.kind,30)||"audio",Number(req.body.position)||0,req.body.settings||{}])).rows[0];await ev(r.workspace_id,req.user.id,"media.track.created",{id:o.id,project_id:r.id});res.status(201).json(o)}catch(e){next(e)}});
app.use("/api",auth);
app.get("/api/workspaces",async(req,res,next)=>{try{res.json((await db("SELECT w.*,wm.role member_role,(SELECT count(*) FROM nexus_apps a WHERE a.workspace_id=w.id) app_count,(SELECT count(*) FROM nexus_automations z WHERE z.workspace_id=w.id) automation_count FROM nexus_workspaces w JOIN nexus_workspace_members wm ON wm.workspace_id=w.id WHERE wm.user_id=$1 ORDER BY w.updated_at DESC",[req.user.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces",async(req,res,next)=>{try{const n=text(req.body.name,100);if(!n)return bad(res,400,"Workspace name is required");const w=(await db("INSERT INTO nexus_workspaces(name,slug,description,owner_id) VALUES($1,$2,$3,$4) RETURNING *",[n,slug(n)+"-"+crypto.randomBytes(3).toString("hex"),text(req.body.description),req.user.id])).rows[0];await db("INSERT INTO nexus_workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner')",[w.id,req.user.id]);await ev(w.id,req.user.id,"workspace.created",{name:n});res.status(201).json(w)}catch(e){next(e)}});
app.get("/api/workspaces/:workspaceId/overview",ws,async(req,res,next)=>{try{const id=req.workspace.id;const [apps,projects,automations,nodes,events,members]=await Promise.all([db("SELECT * FROM nexus_apps WHERE workspace_id=$1 ORDER BY updated_at DESC",[id]),db("SELECT * FROM nexus_projects WHERE workspace_id=$1 ORDER BY created_at DESC",[id]),db("SELECT * FROM nexus_automations WHERE workspace_id=$1 ORDER BY updated_at DESC",[id]),db("SELECT * FROM nexus_builder_nodes WHERE workspace_id=$1 ORDER BY created_at",[id]),db("SELECT e.*,u.display_name FROM nexus_events e LEFT JOIN nexus_users u ON u.id=e.user_id WHERE e.workspace_id=$1 ORDER BY e.created_at DESC LIMIT 100",[id]),db("SELECT u.id,u.email,u.display_name,wm.role FROM nexus_workspace_members wm JOIN nexus_users u ON u.id=wm.user_id WHERE wm.workspace_id=$1",[id])]);res.json({workspace:req.workspace,apps:apps.rows,projects:projects.rows,automations:automations.rows,nodes:nodes.rows,events:events.rows,members:members.rows})}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/projects",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100);if(!n)return bad(res,400,"Project name is required");const r=(await db("INSERT INTO nexus_projects(workspace_id,name,description) VALUES($1,$2,$3) RETURNING *",[req.workspace.id,n,text(req.body.description)])).rows[0];await ev(req.workspace.id,req.user.id,"project.created",{id:r.id,name:n});res.status(201).json(r)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/apps",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100);if(!n)return bad(res,400,"App name is required");const r=(await db("INSERT INTO nexus_apps(workspace_id,name,slug,description) VALUES($1,$2,$3,$4) RETURNING *",[req.workspace.id,n,slug(n)+"-"+crypto.randomBytes(2).toString("hex"),text(req.body.description)])).rows[0];await ev(req.workspace.id,req.user.id,"app.created",{id:r.id,name:n});res.status(201).json(r)}catch(e){next(e)}});
app.patch("/api/apps/:appId",async(req,res,next)=>{try{const r=await db("SELECT a.*,wm.role member_role FROM nexus_apps a JOIN nexus_workspace_members wm ON wm.workspace_id=a.workspace_id WHERE a.id=$1 AND wm.user_id=$2",[req.params.appId,req.user.id]);if(!r.rows[0])return bad(res,404,"App not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_apps SET name=COALESCE(NULLIF($1,''),name),description=COALESCE($2,description),status=COALESCE(NULLIF($3,''),status),config=COALESCE($4,config),updated_at=now() WHERE id=$5 RETURNING *",[text(req.body.name,100),req.body.description==null?null:text(req.body.description),text(req.body.status,30),req.body.config||null,req.params.appId])).rows[0];await ev(r.rows[0].workspace_id,req.user.id,"app.updated",{id:o.id,status:o.status});res.json(o)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/builder/nodes",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const type=text(req.body.type,40)||"logic",label=text(req.body.label,100)||"Node";const r=(await db("INSERT INTO nexus_builder_nodes(workspace_id,app_id,type,label,x,y,config) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[req.workspace.id,req.body.app_id||null,type,label,Number(req.body.x)||80,Number(req.body.y)||80,req.body.config||{}])).rows[0];await ev(req.workspace.id,req.user.id,"builder.node.created",{id:r.id,type});res.status(201).json(r)}catch(e){next(e)}});
app.patch("/api/builder/nodes/:nodeId",async(req,res,next)=>{try{const r=await db("SELECT n.*,wm.role member_role FROM nexus_builder_nodes n JOIN nexus_workspace_members wm ON wm.workspace_id=n.workspace_id WHERE n.id=$1 AND wm.user_id=$2",[req.params.nodeId,req.user.id]);if(!r.rows[0])return bad(res,404,"Node not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_builder_nodes SET x=$1,y=$2,label=COALESCE(NULLIF($3,''),label),config=COALESCE($4,config),updated_at=now() WHERE id=$5 RETURNING *",[Number(req.body.x)||0,Number(req.body.y)||0,text(req.body.label,100),req.body.config||null,req.params.nodeId])).rows[0];res.json(o)}catch(e){next(e)}});
app.delete("/api/builder/nodes/:nodeId",async(req,res,next)=>{try{const r=await db("SELECT n.*,wm.role member_role FROM nexus_builder_nodes n JOIN nexus_workspace_members wm ON wm.workspace_id=n.workspace_id WHERE n.id=$1 AND wm.user_id=$2",[req.params.nodeId,req.user.id]);if(!r.rows[0])return bad(res,404,"Node not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");await db("DELETE FROM nexus_builder_nodes WHERE id=$1",[req.params.nodeId]);await ev(r.rows[0].workspace_id,req.user.id,"builder.node.deleted",{id:req.params.nodeId});res.json({ok:true})}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/automations",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100)||"Untitled automation",trigger=text(req.body.trigger_type,50)||"manual";const r=(await db("INSERT INTO nexus_automations(workspace_id,name,trigger_type,enabled,definition) VALUES($1,$2,$3,$4,$5) RETURNING *",[req.workspace.id,n,trigger,Boolean(req.body.enabled),req.body.definition||{actions:[]}])).rows[0];await ev(req.workspace.id,req.user.id,"automation.created",{id:r.id,name:n});res.status(201).json(r)}catch(e){next(e)}});
app.patch("/api/automations/:automationId",async(req,res,next)=>{try{const r=await db("SELECT a.*,wm.role member_role FROM nexus_automations a JOIN nexus_workspace_members wm ON wm.workspace_id=a.workspace_id WHERE a.id=$1 AND wm.user_id=$2",[req.params.automationId,req.user.id]);if(!r.rows[0])return bad(res,404,"Automation not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_automations SET name=COALESCE(NULLIF($1,''),name),enabled=$2,definition=COALESCE($3,definition),updated_at=now() WHERE id=$4 RETURNING *",[text(req.body.name,100),Boolean(req.body.enabled),req.body.definition||null,req.params.automationId])).rows[0];await ev(r.rows[0].workspace_id,req.user.id,"automation.updated",{id:o.id,enabled:o.enabled});res.json(o)}catch(e){next(e)}});
app.get("/api/events",async(req,res,next)=>{try{const q=text(req.query.workspace_id,80),r=q?await db("SELECT * FROM nexus_events WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 100",[q]):await db("SELECT * FROM nexus_events WHERE user_id=$1 ORDER BY created_at DESC LIMIT 100",[req.user.id]);res.json(r?.rows||[])}catch(e){next(e)}});

// AI agents
app.get("/api/workspaces/:workspaceId/agents",ws,async(req,res,next)=>{try{res.json((await db("SELECT * FROM nexus_ai_agents WHERE workspace_id=$1 ORDER BY updated_at DESC",[req.workspace.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/agents",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,100);if(!n)return bad(res,400,"Agent name is required");const r=(await db("INSERT INTO nexus_ai_agents(workspace_id,name,description,model,config) VALUES($1,$2,$3,$4,$5) RETURNING *",[req.workspace.id,n,text(req.body.description),text(req.body.model,60)||"local",req.body.config||{}])).rows[0];await ev(req.workspace.id,req.user.id,"agent.created",{id:r.id,name:n});res.status(201).json(r)}catch(e){next(e)}});
app.patch("/api/agents/:agentId",async(req,res,next)=>{try{const r=await db("SELECT a.*,wm.role member_role FROM nexus_ai_agents a JOIN nexus_workspace_members wm ON wm.workspace_id=a.workspace_id WHERE a.id=$1 AND wm.user_id=$2",[req.params.agentId,req.user.id]);if(!r.rows[0])return bad(res,404,"Agent not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_ai_agents SET name=COALESCE(NULLIF($1,''),name),description=COALESCE($2,description),model=COALESCE(NULLIF($3,''),model),enabled=$4,config=COALESCE($5,config),updated_at=now() WHERE id=$6 RETURNING *",[text(req.body.name,100),req.body.description==null?null:text(req.body.description),text(req.body.model,60),Boolean(req.body.enabled),req.body.config||null,req.params.agentId])).rows[0];await ev(r.rows[0].workspace_id,req.user.id,"agent.updated",{id:o.id,enabled:o.enabled});res.json(o)}catch(e){next(e)}});
// Files: metadata layer; binary storage can be attached later without changing the model.
app.get("/api/workspaces/:workspaceId/files",ws,async(req,res,next)=>{try{res.json((await db("SELECT * FROM nexus_files WHERE workspace_id=$1 ORDER BY updated_at DESC",[req.workspace.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/files",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,180),p=text(req.body.path,500);if(!n||!p)return bad(res,400,"File name and path are required");const r=(await db("INSERT INTO nexus_files(workspace_id,name,path,size_bytes,mime_type,metadata) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(workspace_id,path) DO UPDATE SET name=EXCLUDED.name,size_bytes=EXCLUDED.size_bytes,mime_type=EXCLUDED.mime_type,version=nexus_files.version+1,metadata=EXCLUDED.metadata,updated_at=now() RETURNING *",[req.workspace.id,n,p,Math.max(0,Number(req.body.size_bytes)||0),text(req.body.mime_type,120)||"application/octet-stream",req.body.metadata||{}])).rows[0];await ev(req.workspace.id,req.user.id,"file.updated",{id:r.id,path:p,version:r.version});res.status(201).json(r)}catch(e){next(e)}});
// Marketplace packages
app.get("/api/workspaces/:workspaceId/marketplace",ws,async(req,res,next)=>{try{res.json((await db("SELECT * FROM nexus_marketplace_items WHERE workspace_id=$1 ORDER BY updated_at DESC",[req.workspace.id])).rows)}catch(e){next(e)}});
app.post("/api/workspaces/:workspaceId/marketplace",ws,async(req,res,next)=>{try{if(!writable(req.workspace.member_role))return bad(res,403,"Write access required");const n=text(req.body.name,120),k=text(req.body.kind,40)||"app";if(!n)return bad(res,400,"Package name is required");const r=(await db("INSERT INTO nexus_marketplace_items(workspace_id,name,kind,description,version,manifest) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[req.workspace.id,n,k,text(req.body.description),text(req.body.version,30)||"0.1.0",req.body.manifest||{}])).rows[0];await ev(req.workspace.id,req.user.id,"marketplace.item.created",{id:r.id,name:n,kind:k});res.status(201).json(r)}catch(e){next(e)}});
app.patch("/api/marketplace/:itemId",async(req,res,next)=>{try{const r=await db("SELECT m.*,wm.role member_role FROM nexus_marketplace_items m JOIN nexus_workspace_members wm ON wm.workspace_id=m.workspace_id WHERE m.id=$1 AND wm.user_id=$2",[req.params.itemId,req.user.id]);if(!r.rows[0])return bad(res,404,"Marketplace item not found");if(!writable(r.rows[0].member_role))return bad(res,403,"Write access required");const o=(await db("UPDATE nexus_marketplace_items SET status=COALESCE(NULLIF($1,''),status),version=COALESCE(NULLIF($2,''),version),manifest=COALESCE($3,manifest),updated_at=now() WHERE id=$4 RETURNING *",[text(req.body.status,30),text(req.body.version,30),req.body.manifest||null,req.params.itemId])).rows[0];res.json(o)}catch(e){next(e)}});
// Workspace metrics and capability inventory
app.get("/api/workspaces/:workspaceId/metrics",ws,async(req,res,next)=>{try{const [events,apps,agents,files,autos,members]=await Promise.all([db("SELECT count(*)::int n FROM nexus_events WHERE workspace_id=$1",[req.workspace.id]),db("SELECT count(*)::int n FROM nexus_apps WHERE workspace_id=$1",[req.workspace.id]),db("SELECT count(*)::int n FROM nexus_ai_agents WHERE workspace_id=$1",[req.workspace.id]),db("SELECT count(*)::int n FROM nexus_files WHERE workspace_id=$1",[req.workspace.id]),db("SELECT count(*)::int n FROM nexus_automations WHERE workspace_id=$1",[req.workspace.id]),db("SELECT count(*)::int n FROM nexus_workspace_members WHERE workspace_id=$1",[req.workspace.id])]);res.json({events:events.rows[0].n,apps:apps.rows[0].n,agents:agents.rows[0].n,files:files.rows[0].n,automations:autos.rows[0].n,members:members.rows[0].n})}catch(e){next(e)}});
app.use(express.static(path.join(__dirname,"public")));app.use((req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(500).json({error:prod?"Internal server error":err.message})});
init().then(()=>app.listen(PORT,()=>console.log("NEXUS listening on "+PORT))).catch(e=>{console.error(e);process.exit(1)});